/*
 * gen_versions.js — Phase 32 B: build the display-only "Versions" reference data.
 *
 * Source: KanjiVG VARIANT SVG files (…-Kaisho.svg etc.). These are exactly the
 * files the Phase 30 bug was about — so this pipeline is deliberately walled off
 * from stroke practice: output goes to data/versions/ (never data/kanji/), as
 * pre-cleaned static SVG IMAGES (stroke-number labels stripped), consumed only by
 * an <img> tag in js/versions.js. Nothing here is ever parsed as stroke data.
 *
 * Classes kept (appearance-changing):
 *   kaisho  楷書   — calligraphic style      (Kaisho, KaishoVtLst, KaishoVt3, …)
 *   hyougai 表外   — alternate glyph form    (Hyougai, HyougaiKaisho)
 *   jinmei  人名   — name-use glyph form     (Jinmei*)
 * Pure stroke-ORDER variants (VtLst/HzFst/…) look identical as static images and
 * are excluded. KanjiVG has no true cursive (行書/草書) — flagged, omitted.
 *
 * Run from repo root. Requires the KanjiVG snapshot (see KVG path).
 */
const fs = require("fs");
const path = require("path");
const KVG = "/tmp/claude-0/-home-user-Kanji---App/6bf433aa-e9f0-518b-9a85-c7530c860182/scratchpad/kvg_extract/kanjivg-master/kanji";

global.window = {};
for (const f of ["kanji-meta", "kanji-gen-1", "kanji-gen-2", "kanji-gen-3", "kanji-gen-4", "kanji-gen-5"]) require(process.cwd() + "/data/" + f + ".js");
const chars = global.window.KANJI_META.map(m => m.char);

const all = fs.readdirSync(KVG);
const byHex = {};
all.forEach(f => { const m = f.match(/^([0-9a-f]{5})-(.+)\.svg$/); if (m) (byHex[m[1]] = byHex[m[1]] || []).push(m[2]); });

// pick at most one file per class, preferring the plainest suffix
function classify(sufs) {
  const pick = (cands) => cands.find(c => sufs.includes(c));
  return {
    kaisho: pick(["Kaisho", "KaishoVtLst", "KaishoVt3", "KaishoVt4", "KaishoHzFst", "KaishoHzFstLeRi", "KaishoVtLst2"]),
    hyougai: pick(["Hyougai", "HyougaiKaisho"]),
    jinmei: pick(["Jinmei", "JinmeiKaisho"]),
  };
}

function cleanSvg(txt) {
  let s = txt.replace(/<\?xml[\s\S]*?\?>/, "").replace(/<!--[\s\S]*?-->/g, "").replace(/<!DOCTYPE[\s\S]*?\]>/, "");
  // drop the stroke-number labels group entirely (display should be the glyph only)
  s = s.replace(/<g[^>]*StrokeNumbers[\s\S]*?<\/g>/, "");
  // strip kvg:* attributes — their namespace declaration is gone, and a strict XML
  // parse (as an <img> SVG document) would fail on undeclared prefixes
  s = s.replace(/\s+kvg:[\w-]+="[^"]*"/g, "");
  return s.trim();
}

const outDir = "data/versions";
fs.mkdirSync(outDir, { recursive: true });
const map = {};
let files = 0;
chars.forEach(ch => {
  const hex = ch.codePointAt(0).toString(16).padStart(5, "0");
  const sufs = byHex[hex];
  if (!sufs) return;
  const cls = classify(sufs);
  const entry = [];
  for (const k of ["kaisho", "hyougai", "jinmei"]) {
    if (!cls[k]) continue;
    const src = path.join(KVG, hex + "-" + cls[k] + ".svg");
    const out = hex + "-" + k + ".svg";
    fs.writeFileSync(path.join(outDir, out), cleanSvg(fs.readFileSync(src, "utf8")));
    entry.push(k);
    files++;
  }
  if (entry.length) map[ch] = entry;
});

fs.writeFileSync("data/kanji-versions.js",
  "/* auto-generated by tools/gen_versions.js from KanjiVG variant files.\n" +
  " * DISPLAY-ONLY reference forms (data/versions/*.svg) — never stroke-practice data. */\n" +
  "window.KANJI_VERSIONS=" + JSON.stringify(map) + ";\n");

console.log("kanji with versions:", Object.keys(map).length, "| svg files written:", files);
const dist = {};
Object.values(map).forEach(e => e.forEach(k => dist[k] = (dist[k] || 0) + 1));
console.log("per class:", JSON.stringify(dist));
console.log("線:", JSON.stringify(map["線"]), "之:", JSON.stringify(map["之"]), "煙:", JSON.stringify(map["煙"] || null));
